# Generated by Django 3.2.6 on 2021-08-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210813_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descreption',
            new_name='description',
        ),
    ]
