# Generated by Django 3.2.6 on 2021-09-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210911_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-total_ratio', '-total_vote', 'title']},
        ),
    ]
